### ISSUE TITLE
Paytm is not defined

### ISSUE THREAD

**Issue by gauravradadiya** [ArunYogi/paytm-cordova-plugin#15]
I declared paytm in declarations.d.ts as per instruction, and use paytm.startPayment() method, 
but it throws an error, 

> paytm is not defined.

Is there any thing that I missed? Can you please help me for the same?

![screenshot 9](https://user-images.githubusercontent.com/8263790/50559068-48e7b900-0d19-11e9-86fe-99c0a5594b1f.png)

**Comment by gauravradadiya** [comment]
Please paste here working demo code for ionic version > 2, So I can look into it for solving issue.

**Comment by ArunYogi** [comment]
Add below line to declaration.d.ts file
```
declare var paytm : any;
```

Dont add below line in declaration.d.ts. Add this line in service/page where you actually starting the transaction.
```
paytm.startPayment(options, successCallback, failureCallback);
```

**Comment by gauravradadiya** [comment]
I have done the same, "Paytm is not defined" this error resolved somehow paytm.startPayment function will not redirect to paytm transaction page, but remains on same page, neither successCallback nor failureCallback.

I passed options as below, 

```
this.options.REQUEST_TYPE = "DEFAULT";
    this.options.MID = "********************";
    this.options.ORDER_ID = "CNP0101";
    this.options.CUST_ID = "USER01";
    this.options.EMAIL = "someone@gmail.com";
    this.options.MOBILE = "99******84";
    this.options.INDUSTRY_TYPE_ID = "Retail";
    this.options.CHANNEL_ID = "WAP";
    this.options.TXN_AMOUNT = "10";
    this.options.WEBSITE = "WEBSTAGING";
    this.options.CALLBACK_URL = "https://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID=" + this.options.ORDER_ID;
    this.options.ENVIRONMENT = "staging";
this.options.CHECKSUMHASH = ********************************************************;
```
Please help me for the same. @ArunYogi

**Comment by ArunYogi** [comment]
@gauravradadiya , any error thrown in console or in mobile logs ? could you also paste the code you are using to trigger the payment transaction.

**Comment by gauravradadiya** [comment]
@ArunYogi , No error thrown in console or mobile logs, My question is by using startPayment function it will automatically redirect to paytm transaction page or need to pass some other parameter for the same?

Because I created a demo app for testing paytm, and I used same code given by you in [NPMJS url](https://www.npmjs.com/package/cordova-plugin-paytm).

**Comment by ArunYogi** [comment]
"startPayment(..)" is enough, automatically webview control will be transferred to Paytm plugin. If no error in console log or mobile log, then the "startPayment" method is not executed itself.

**Comment by gauravradadiya** [comment]
[Here](https://github.com/ArunYogi/paytm-cordova-plugin/files/2729184/home.ts.zip) My home.ts page , can you please check it once, if I made any mistake? @ArunYogi

**Comment by ArunYogi** [comment]
Check this attached file. [home.ts.zip](https://github.com/ArunYogi/paytm-cordova-plugin/files/2720788/home.ts.zip)
I have modified few things, further i have some alerts to see the response status. Check the console logs and mobile log to see any discrepancies.

**Comment by gauravradadiya** [comment]
Sir I have done changes as you said, but I think somehow startPayment does not executing, no any alert shown, I put log after startPayment function, it shown in console but there are no other error shown in console when I run this demo to android.

When I run using ionic serve then browser thrown "ERROR ReferenceError: paytm is not defined", but not in android device. Should I share demo project with you?

**Comment by prabas08** [comment]
I am also facing the same problem. startPayment function call is not taking me to paytm page. Also I do not see any error in console.

Below is the option I pass to this function call

**{"MID":"uMNODV19427114529803","ORDER_ID":"MERC10024","CUST_ID":"ABC13","INDUSTRY_TYPE_ID":"Retail","CHANNEL_ID":"WAP","TXN_AMOUNT":"1","WEBSITE":"APPSTAGING","CALLBACK_URL":"https://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID=MERC10024","EMAIL":"niormal@gmail.com","MOBILE_NO":"123456789","CHECKSUMHASH":"afBJiNijrIL7xA+j484HEoo/zcNQMeeoUeA3u4QRNBc6mi0wckkdIjHwjhmtj3OsODvZWieiAChzZUtaDChIBMsrl7t4WC5tZwxFy76AVNQ=","ENVIRONMENT":"staging","REQUEST_TYPE":"DEFAULT"}**

**Comment by ArunYogi** [comment]
@prabas08 @gauravradadiya ,
what's the cordova-android version you are using?
Could you give me the android mobile logs to see the initiation of plugin logs.

**Comment by prabas08** [comment]
@ArunYogi ,
          I use cordova version 8.0.0
Please find attached, the android mobile log file
[androidlog.txt](https://github.com/ArunYogi/paytm-cordova-plugin/files/2723093/androidlog.txt)

at line 9925, you can see the below error

"W/ResourceType(10222): No package identifier when getting value for resource number 0x00000000"

This is where I call the function paytm.startPayment(result, function(response)... );

**Comment by ArunYogi** [comment]
I mean the cordova-android version used to build for android apk file.
Could you also see whether folder named `com.paytm` was created inside `{projectfolder}/platforms/android/build/intermediates/exploded-aar` like this
<img width="261" alt="screenshot 2019-01-03 14 54 01" src="https://user-images.githubusercontent.com/23559391/50630600-7e81e180-0f67-11e9-901a-b5ddd4b7a537.png">.

Further this plugin has to be modified for cordova-android =>v7, as the structure has been changed by cordova-android team at this version.

**Comment by gauravradadiya** [comment]
@ArunYogi  I am using 8.1.2 (cordova-lib@8.1.1) and cordova-android@~7.1.1
and also log file I attached here,

[verbose.txt](https://github.com/ArunYogi/paytm-cordova-plugin/files/2723198/verbose.txt)

error I can see, 
01-03 14:45:43.340 10612-10762/io.ionic.starter W/ResourceType: No package identifier when getting value for resource number 0x00000000

![screenshot 10](https://user-images.githubusercontent.com/8263790/50631215-8d699380-0f69-11e9-89f8-40e7dd56ef6e.png)
![screenshot 11](https://user-images.githubusercontent.com/8263790/50631216-8d699380-0f69-11e9-9526-851da98ae3f3.png)

and there are no other folders I can see into platforms/android/build

**Comment by ArunYogi** [comment]
@gauravradadiya , {projectfolder}/platforms/android/build/ is the folder used to place content necessary for building an apk file when you run `cordova build android`. Being that folder empty, not sure whether project has been built properly. 
Further as you are using v7.1, this plugin has to be tested with that version, will do that soon.

**Comment by prabas08** [comment]
Installed platforms:
  android 7.0.0

The folder structure has changed for this version I guess.. in earlier version it was under android/build. but now it  gets compiled under **platforms\android\app\build\**. Below all the folders under **app\build** directory

01/03/2019  12:34 PM    <DIR>          generated
01/03/2019  12:34 PM    <DIR>          intermediates
01/03/2019  12:35 PM    <DIR>          outputs
01/03/2019  12:34 PM    <DIR>          tmp

Also I do not see folder "exploded-aar" and "com.paytm" under it. I do not have android studio installed..

I installed android SDK and build project from CLI

**Comment by gauravradadiya** [comment]
Yes true, @prabas08  I also can not see "exploded-aar" under **platforms\android\app\build**

I also build it using CLI,

![screenshot 12](https://user-images.githubusercontent.com/8263790/50632503-1d114100-0f6e-11e9-9475-0cb95ed40570.png)

**Comment by prabas08** [comment]
@ArunYogi FYI.. I see the files you listed under gradle folder.

**C:\Users\prabakaran_k\.gradle\caches\transforms-1\files-1.1\pgplussdk-1.2.3.aar\84b5b7d172aca5cf19f737b0c5ac7224**

jars, res, AndroidManifest.xml,R.txt

Below lines are some logs from **manifest-merger-debug-report.txt** which gets updated on building the project

activity#com.paytm.pgsdk.PaytmPGActivity
ADDED from C:\Users\prabakaran_k\PhoneGap\testAPP\platforms\android\app\src\main\AndroidManifest.xml:16:9-165
MERGED from [com.paytm:pgplussdk:1.2.3] C:\Users\prabakaran_k\.gradle\caches\transforms-1\files-1.1\pgplussdk-1.2.3.aar\84b5b7d172aca5cf19f737b0c5ac7224\AndroidManifest.xml:13:9-16:47
MERGED from [com.paytm:pgplussdk:1.2.3] C:\Users\prabakaran_k\.gradle\caches\transforms-1\files-1.1\pgplussdk-1.2.3.aar\84b5b7d172aca5cf19f737b0c5ac7224\AndroidManifest.xml:13:9-16:47

**Comment by prabas08** [comment]
I found the reason. C:\Users\prabakaran_k\PhoneGap\testApp\platforms\android\app\src\main\res\values\paytmcordova.xml did not have string elements under resources element.

So changing the paytmcordova.xml as below, resolved the issue.

```
<?xml version='1.0' encoding='utf-8'?>
<resources>
<string name="paytm_merchant_id">uMNODV15475114529803</string>
<string name="paytm_industry_type_id">Retail</string>
<string name="paytm_website">APPSTAGING</string>
</resources>
```

But now I get checksumhash mistmatch error, which I need to check why it gives that error.

@gauravradadiya : I hope make the above change will work for you as well.

**Comment by gauravradadiya** [comment]
@prabas08 I have changed **strings.xml** because changing in paytmcordova.xml as per you said not working, 

but after that I got same error "checksumhash mistmatch " as you are facing. 
So if you get any solution for it please let me know.

**Comment by prabas08** [comment]
@ArunYogi Please let us know if the change we made is valid. Also please let me know if you think that some thing else is missing, so that checksum mismatch error arises.

**Comment by ArunYogi** [comment]
@prabas08 @gauravradadiya , 
For now If you do below changes, you should be able to proceed further.
1) Remove `platforms` folder from workspace.
2) Change `plugins/cordova-plugin-paytm/plugin.xml` as shown in the pic.
<img width="983" alt="screenshot 2019-01-04 12 02 05" src="https://user-images.githubusercontent.com/23559391/50676114-a41af380-1018-11e9-8e79-9d664e61f107.png">
3) Now add necessary platform again, this should solve the issue. 
Let me know the result.

**Comment by gauravradadiya** [comment]
@ArunYogi  I have done changes as you said, but I still get below response,

Transaction status TXN_FAILURE
Transaction Failed for reason Paytm checksum mismatch.

**Comment by ArunYogi** [comment]
@gauravradadiya , ok atleast now plugin is working, fine. 
You need to check what info you are sending for checksum mismatch with paytm documents. I hope "ENVIRONMENT" is not part of that checksum creation.

**Comment by prabas08** [comment]
@gauravradadiya remove REQUEST_TYPE from options. The options should have only CHECKSUMHASH as extra thing to be passed to startPayment() method. That works for me.

Now the problem I have is, after successful transaction, paytm is not redirecting back to my app. I need to check that.

@ArunYogi what is the purpose of REQUEST_TYPE option? I do not see it being used anywhere in your code. Also this is not part of paytm options.

**Comment by ArunYogi** [comment]
@prabas08, "REQUEST_TYPE" is needed for paytm as per their documentation, cordova plugin does nothing with that and related to that. Regarding "Paytm not redirecting to app", you have to check with Paytm team, they have do some configuration for your MID for these activities to happen.

**Comment by prabas08** [comment]
@ArunYogi: OKAY.. Thank you for the information.

**Comment by gauravradadiya** [comment]
@prabas08  I still have same error "Paytm checksum mismatch", I am not passing "ENVIRONMENT" for generate checksum,

Can you please send me checksum generation request parameters which you are sending and also all parameters which you are passing with startPayment() method?

**Comment by prabas08** [comment]
@gauravradadiya: ENVIRONMENT (I missed to inform earlier) AND CHECKSUMHASH are required as additional options for startPayment() function.

Should not pass ENVIRONMENT for generate checksum(you are correct). ENVIRONMENT field is just for cordova-plugin purpose to identify the stage.

Below are options that I pass to generate checksum:

        paramarray['MID'] = 'merchant ID'; //Provided by Paytm
        paramarray['ORDER_ID'] = clientQuery.orderID; //unique OrderId for every request
        paramarray['CUST_ID'] = clientQuery.custID;  // unique customer identifier
        paramarray['INDUSTRY_TYPE_ID'] = 'Retail'; //Provided by Paytm
        paramarray['CHANNEL_ID'] = 'WAP'; //Provided by Paytm
        paramarray['TXN_AMOUNT'] = '1.00'; // transaction amount
        paramarray['WEBSITE'] = 'APPSTAGING'; //Provided by Paytm
        paramarray['CALLBACK_URL'] = "https://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID="+paramarray['ORDER_ID'];
        paramarray['EMAIL'] = clientQuery.custEmail; // customer email id
        paramarray['MOBILE_NO'] = clientQuery.custPhone; // customer 10 digit mobile no.

**Comment by gauravradadiya** [comment]
@prabas08  can you please send me a demo for the same, I still struggling with same error. 

If you can give me your skype id, it would be great.

**Comment by vickytak** [comment]
@gauravradadiya i am facing same issue, while i change callback url from "https://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID="+paramarray['ORDER_ID']; to my site callback url, error gone, so what is wrong in callback url

**Comment by gauravradadiya** [comment]
@vickytak  Yes you are right when I remove callback url , then checksum mismatch error gone. I am searching for the same that what's wrong with paytm callback URL.

**Comment by vickytak** [comment]
@gauravradadiya, As i debug the error, app shows 404 not found error for paytm callback url, in result it shows checksum mismatch error

**Comment by prabas08** [comment]
> @prabas08, **Regarding "Paytm not redirecting to app", you have to check with Paytm team, they have do some configuration for your MID for these activities to happen.**

@ArunYogi : When I mailed paytm team mentioning the redirecting issue after successful transaction, dev support team said they do not support for cordova, which was confusing to me, as I am already able to make successful transaction.

Today they sent me an other mail mentioning some HTML form.
![image](https://user-images.githubusercontent.com/34547590/50820784-8ff62f80-1353-11e9-8527-cd19ff953f7c.png)

I do not understand why they have sent this.

I think they havent understood my request. Could you please provide your communication information with paytm dev support team regarding redirection issue, so that I can request in the same way to them?

**Comment by ArunYogi** [comment]
@prabas08 , Paytm doesn't have their own official cordova plugin for us to use. So I have created paytm cordova plugin (using paytm's libraries of respective platform) for my need and maintaining it. So I can support you for issues related to the plugin and not related to the paytm's library or functioning. 

When I deal with Paytm, I don't mention cordova, When I mention cordova plugin, they are getting defensive and rejects to listen further. So I just mention that "Issue faced in android/ios library in WAP environment" and resolve the issue.

I suggest the same for you.

**Comment by vickytak** [comment]
Hi @ArunYogi , can you help me with checksum mismatch error.  i am trying from last 4 days to resolve this issue, but no success.

**Comment by ArunYogi** [comment]
@vickytak , If you have followed all the steps mentioned in the Readme file and conversation in this issue, then "Checksum mismatch error" can be solved by Paytm team only. You have to contact Paytm for this. Give them more details about the issue like request body.

**Comment by gauravradadiya** [comment]
@prabas08  Can you please share me your contact details If possible ?

**Comment by prabas08** [comment]
> @prabas08 Can you please share me your contact details If possible ?

9600333646

**Comment by ArunYogi** [comment]
@prabas08 , paste your sample code on how you are creating checksum in this post, so lots of person can help you (not just me).

**Comment by pachu4u** [comment]
@ArunYogi : 

I had earlier integrated paytm using ur plugin and it worked great. But it suddenly stopped working. I am guessing because of cordova android version. I am on 7.1.4. Not sue what was the earlier version.

Any way i followed this thread and I tried the solution u suggested about prefixing app/src/main. But it did not resolve the problem. Could you please help me with this issue

**Comment by pachu4u** [comment]
@ArunYogi,

I see that you have created a new version for cordova android >7. I am trying to install using the below command

cordova plugin add cordova-plugin-paytm --variable MERCHANT_ID=fmTVWE90843006989078 --variable INDUSTRY_TYPE_ID=Retail --variable WEBSITE=WEBSTAGING --save

but getting this error while installing 

Unexpected close tag
Line: 29
Column: 12
Char: >

I figured it out. in plugin.xml - line 29 not closed correctly
<engine name="cordova-android" version=">=7.0.0"/>

**Comment by ArunYogi** [comment]
@pachu4u , I have release 0.0.10 with corrected plugin.xml file.

**Comment by RobertRajcool** [comment]
i'm facing this issue,
![paytm_error](https://user-images.githubusercontent.com/17331229/56859909-ab428480-69ae-11e9-98bc-9cfbec7bcfeb.png)

**home.ts**
`import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
declare var paytm : any;

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController) {

  }
  suc(response) {
    console.log(response)
  }
  submit(){
    var options = {
      "MID": "VTjjEw61927266833738",
        "ORDER_ID": "ORDER234545",
        "CUST_ID": "CUSTOMER2123",
        "TXN_AMOUNT": "1",
        "CHANNEL_ID": "WEB",
        "INDUSTRY_TYPE_ID": "Retail",
        "CALLBACK_URL": "https://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID=ORDER234545",
        "WEBSITE": "WEBSTAGING",
        "MOBILE_NO": "9790584839",
        "EMAIL": "doss.cclawrance226@gmail.com",
         "CHECKSUMHASH": "xVZOdtw179TN0bzKOsTYKFLJPuMiRaeEU/9UZTObUQWbrLeA8ZsnTaT5GZ4ULJ1ZifjgUt3ZYsQD0oyXzjngeb8gxP0qeW00OYKfnFKK8/4="
    }
    paytm.startPayment(options, this.suc, this.suc);

  }

}
`

can you please help resolve this

@ArunYogi  @YaMo97 FYI

**Comment by RobertRajcool** [comment]
@ArunYogi  i have resloved this issue so i'm closing this issue

**Comment by siva563** [comment]
@ArunYogi  I am using Ionic 4, It is saying 

In my .ts

`declare var paytm: any;`

`ReferenceError: Can't find variable: paytm`

could you please help me solve this issue, I am using both iOS and Android. Thanks  a lot.

**Comment by siva563** [comment]
@RobertRajcool  did you get any solutions ?

**Comment by ArunYogi** [comment]
@RobertRajcool , please don't comment on closed task. Create a new one issue, so that easy to identify open concern and address it.
I haven't tried this plugin with ionic 4. Could you check whether this plugin got installed properly while u do `ionic cordova plugin add cordova-plugin-paytm ...'?

**Comment by siva563** [comment]
Yes, installed. 
<img width="386" alt="Screenshot 2019-05-15 at 3 37 38 PM" src="https://user-images.githubusercontent.com/11851911/57767702-9e9c8b00-7727-11e9-85ba-d491a8d679e5.png">

so I am getting error like Paytm is not defined. could you please help me if possible thank you so much.

**Comment by RobertRajcool** [comment]
@ArunYogi  okay Arun

@siva563 i'm using Ionic3 seems works for me

**Comment by siva563** [comment]
how you resolved this issue, even in ionic 3 ? I will give a try in ionic 4 ?

**Comment by siva563** [comment]
I am trying almost, I am getting error 
below :  Redirecting back to app.

@ArunYogi  could you please help me.

**Comment by ArunYogi** [comment]
@siva563 , Please dont report in closed issues. Please create a new issue for better tracking and response. Your are getting stuck with "redirect back to app" message or issue in redirecting to your app? . Please create new issue for any new queries

**Comment by siva563** [comment]
Sorry, I will create new Issue.

**Comment by manmohanagarwal4** [comment]
@ArunYogi Sir I have almost done but one minor issue has been left that is checksum is invalid please resolve this issue.

**Comment by manmohanagarwal4** [comment]
why checksum is invalid i have all field include to create checksum

**Comment by ArunYogi** [comment]
@manmohanagarwal4, please dont comment on closed issues. Create a new question in github of type question. While posting your query, please give some details about the information you are sending to library.

**Comment by abhishektomer** [comment]
hello,

`ERROR ReferenceError: paytm is not defined
    at SafeSubscriber._next (payment.page.ts:324)`

even I have declared 

`declare var paytm: any;`

in my decleration.d.ts

i am using cordova-plugin-paytm

![image](https://user-images.githubusercontent.com/25544041/66803890-98ad0f00-ef3e-11e9-9492-645d2dd0661c.png)

**Comment by ArunYogi** [comment]
> hello,
> 
> `ERROR ReferenceError: paytm is not defined at SafeSubscriber._next (payment.page.ts:324)`
> 
> even I have declared
> 
> `declare var paytm: any;`
> 
> in my decleration.d.ts
> 
> i am using cordova-plugin-paytm
> 
> ![image](https://user-images.githubusercontent.com/25544041/66803890-98ad0f00-ef3e-11e9-9492-645d2dd0661c.png)

Please dont comment on closed issue..
check the plugin installation, I dont think, the plugin was installed properly. uninstall and install plugin once

**Comment by manojbharti** [comment]
@ArunYogi please help me to use this plugin with latest version of ionic.

**Comment by kapilSoni101** [comment]
@gauravradadiya and @ArunYogi :can you tell me how to generate CHECKSUMHASH ?
